### ISSUE TITLE
BlastEm fails to load files from "Load Content" - Section is bigger than remaining space in file%

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/blastem#28]
When BlastEm loads a game scanned in the "Mega Drive - Genesis" section of RetroArch, BlastEm works like a charm. 
When Blastem loads a game from the "Load Content" section of RetroArch, it loses its mind and crashes RetroArch.

RetroArch Output before crashing: https://pastebin.com/nSi0wX3Y
Note that the output is loading of two games from the Database, and then one game from "Load Content".

**Comment by hizzlekizzle** [comment]
You may have noticed that the first 2 loads were actually using the Picodrive core. Did you figure out what was causing the "Section is bigger than remaining space in file%" issue, though?
